### ISSUE TITLE
Which API should I call to disable initial screenshot?

### ISSUE THREAD

**Issue by raymondctc** [Instabug/Instabug-Android#122]
`Instabug.setAttachmentTypesEnabled(..);` is marked as deprecated in latest version

**Comment by ramiimagdi** [comment]
Hey @raymondctc 

Actually the API you shared with me earlier is the correct API and it's not repricated:

// Arguments:initialScreenshot, extraScreenshot, galleryImage & ScreenRecording
`Instabug.setAttachmentTypesEnabled(true, true, false, false);`

However, if it doesn't work with you, we'll need to troubleshoot the issue here. Can you please confirm that it isn't working?

**Comment by raymondctc** [comment]
Yes, that’s actually working. But it’s marked with the deprecated annotation, I was wondering.

**Comment by ramiimagdi** [comment]
Oh, I get what you mean now, many apologies for the confusion here, the un-deprecated API is as follows:
`BugReporting.setAttachmentTypesEnabled(false, true, true, true);`

**Comment by ramiimagdi** [comment]
@raymondctc Please feel free to reach out to us again if you need any help at all. Have a great day 🙏🏻
