### ISSUE TITLE
BugReporting onSdkDismissCallback is not called when prompt options dialog is dismissed

### ISSUE THREAD

**Issue by bdentino** [Instabug/Instabug-Android#136]
### Steps to Reproduce the Problem
1. Add a callback to listen for sdk dismissal via `BugReporting.setOnDismissCallback`.
2. Invoke the SDK prompt options dialog.
3. Dismiss the prompt options dialog by pressing outside of the form.

### Expected Behavior
The callback should be executed.

### Actual Behavior
The callback is not executed. Interestingly, the deprecated callback handler is actually executed twice.

### Instabug integration code
```
            new Instabug.Builder(this, INSTABUG_TOKEN)
                    .setInvocationEvents(InstabugInvocationEvent.SHAKE)
                    .build();
 
            // Deprecated
            Instabug.setOnSdkDismissedCallback((OnSdkDismissedCallback.DismissType dismissType, Bug.Type type) -> {
                Log.i("Deprecated callback invoked");
            });

            BugReporting.setOnDismissCallback((OnSdkDismissCallback.DismissType dismissType, OnSdkDismissCallback.ReportType reportType) -> {
                Log.i("New callback invoked");
            });
```

### SDK Version
8.0.8

### Android Version
26

### Device Model
Samsung Galaxy S8+

**Comment by ramiimagdi** [comment]
Hey @bdentino, thank you for reaching out to us!
Please allow me some time to investigate this further and get back to you.

**Comment by kamelnabil** [comment]
Hey, Brian (@bdentino),
I'm jumping in here for Rami. 
As for the deprecated API, it works fine for what you want to accomplish. The other API only works with the bug reporting. It doesn't work with the prompt options dialog and this is not a bug. We are tailoring that by design. If you still want to know if the user dismisses the Prompt options dialog, you can use the deprecated API. 
We don't have any plans to remove it in the near future and when we remove it, we will definitely provide an alternative.

Please let me know if I can help you more here. I will be glad to help 🙂

**Comment by ramiimagdi** [comment]
Hello again @bdentino, please feel free to reopen this thread again if you have any further concerns. We'd more than happy to help you out 😊
