### ISSUE TITLE
OutOfMemoryError in Encryptor

### ISSUE THREAD

**Issue by Axrorxoja** [Instabug/Instabug-Android#208]
AndroidX
compileSdkVersion 28
buildToolsVersion "28.0.3"
instabug version 8.4 
<img width="921" alt="Screen Shot 2019-07-29 at 10 56 54 AM" src="https://user-images.githubusercontent.com/5182036/62024882-db890180-b1ef-11e9-81f2-3b1e5ec6c2f0.png">

**Comment by mzelzoghbi** [comment]
Hi @Axrorxoja, Thanks for reporting this, Can you provide us with the device name/model/os-version that throwing this issue? Also is there a reproduce steps for reproducing this issue?

**Comment by Axrorxoja** [comment]
Hi @mzelzoghbi thank you too :) for great tooling, 
<img width="411" alt="Screen Shot 2019-07-30 at 9 53 59 AM" src="https://user-images.githubusercontent.com/5182036/62101833-3f72ff00-b2b0-11e9-9711-da42dcfe9f02.png">
<img width="228" alt="Screen Shot 2019-07-30 at 9 54 11 AM" src="https://user-images.githubusercontent.com/5182036/62101835-3f72ff00-b2b0-11e9-86b2-41477b093e2e.png">

**Comment by quibi-jlk** [comment]
I'm seeing the same stack trace reported, but with two different devices: Moto G4 Play and Moto Z Droid on OS 6 and 7. Unfortunately, I don't have repro steps at the moment, but would be happy to provide any other info you need here.

**Comment by Muhammadyoussef** [comment]
@Axrorxoja @quibi-jlk 
[9.1.1](https://github.com/Instabug/Instabug-Android/releases/tag/9.1.1) has rolled out and it has the fix for this issue. 

To consume the latest changes please update your dependency as follows:
`implementation 'com.instabug.library:instabug:9.1.1'`

I'll close this issue for now but please feel free to re-open it if the issue still occurs.
