### ISSUE TITLE
android.view.View android.view.View.findViewById(int)

### ISSUE THREAD

**Issue by Axrorxoja** [Instabug/Instabug-Android#241]
<img width="828" alt="Screen Shot 2019-10-13 at 9 44 40 PM" src="https://user-images.githubusercontent.com/5182036/66718931-d73daf00-ee02-11e9-8a6e-423478c152dd.png">
latest version Instabug 8.7.0

**Comment by Muhammadyoussef** [comment]
Hi @Axrorxoja,

Would you please use `implementation com.instabug.library:instabug:8.7.0` and let us know if this issue still occurs 🙏

**Comment by Axrorxoja** [comment]
@Muhammadyoussef it was happen in 8.7.0 version !

**Comment by Muhammadyoussef** [comment]
Hi @Axrorxoja , 

First of all, please accept our sincerest apologies for taking some time to come up with a fix for your issue. 
The stacktrace does not correspond to `8.7.0`. However, the good news here is that we were able to create a snapshot that has the fix for you.

The following snapshot has the fix
`8.7.0.22-SNAPSHOT`

To grab the snapshot, please add the following to your code:

```
repositories {
    maven {
        // TODO add this only if interested in getting SNAPSHOT releases
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```
```
dependencies {
    implementation com.instabug.library:instabug:8.7.0.22-SNAPSHOT
}
```
Please give it a try, and let me know if it solves the issues you have. Thank you 😊

**Comment by Muhammadyoussef** [comment]
Hi @Axrorxoja,
I'll close this issue for now. Please feel free to reopen it if you still encounter this issue
