### ISSUE TITLE
Crash in InstabugAnnouncementSubmitterService on wake_lock permission

### ISSUE THREAD

**Issue by edenman** [Instabug/Instabug-Android#258]
### Steps to Reproduce the Problem
Launch app on API 23 emulator

### Expected Behavior
App launches

### Actual Behavior
 java.lang.RuntimeException: Unable to start service com.instabug.survey.announcements.network.InstabugAnnouncementSubmitterService@7c60a11 with Intent { cmp=com.envoy.app/com.instabug.survey.announcements.network.InstabugAnnouncementSubmitterService }: java.lang.SecurityException: Neither user 10062 nor current process has android.permission.WAKE_LOCK.

### Instabug integration code
```  open fun initInstabug() {
    Instabug.Builder(this, BuildConfig.INSTABUG_TOKEN)
      .setConsoleLogState(Feature.State.ENABLED)
      .setInvocationEvents(InstabugInvocationEvent.SHAKE)
      .setUserDataState(Feature.State.DISABLED)
      .build()
    Instabug.setColorTheme(InstabugColorTheme.InstabugColorThemeLight)
    Instabug.setDebugEnabled(BuildConfig.DEBUG)
  }
```
We also have this in our AndroidManifest:
```
    <uses-permission android:name="android.permission.WAKE_LOCK" tools:node="remove"/>
```

### SDK Version
8.7.2

### Android Version
23

### Device Model
emulator

**Comment by mzelzoghbi** [comment]
Hello @edenman , Thanks for reporting this.
We can see that the issue is due to removing `WAKE_LOCK` permission which is required by our SDK to work. 
This permission we added to support `JobIntentService` after Oreo was released and limiting the background services.  These services are used to handle SDK network requests like sessions, surveys, announcements, bug reports, etc

Removing the whole line or the remove node should solve the issue. 

Thank You.
