### ISSUE TITLE
invoke NEW_CHAT

### ISSUE THREAD

**Issue by pouriabagheri** [Instabug/Instabug-Android#262]
### Steps to Reproduce the Problem
 UPGRADE 8.0.6  to 9.0.4

### SDK Version
 9.0.4

### [Optional] Project That Reproduces the Issue
We need to invoke new chat from app it was available through `                BugReporting.invoke(InvocationMode.NEW_CHAT)` but it is no longer available in the new version. I couldn't find the new implementation.

The closest was `Replies.show()` but it is only for existing chat not for creating a new chat.

Also Instabug Builder no longer takes `setCrashReportingState(Feature.State.ENABLED)`. Is there a new implementation for this ? 

Thank you.

**Comment by Korazy** [comment]
Hey @pouriabagheri, thanks for reaching out to us!

Regarding your first question, we recently changed the way chats work (around 4-5 months ago), rather than start a new chat, users can send in questions that look a bit like a bug report using the ask a question button in the prompt options. You can manually show the question form using `BugReporting.show(BugReporting.ReportType.QUESTION)`

As for your question regarding the crash reporting, the new API is `CrashReporting.setState(Feature.State.ENABLED);`

If you have any other questions, please feel free to reach out to us. Happy new year 🎆
