### ISSUE TITLE
Crash : Given work is not active: JobWorkItem{id=1 intent=Intent { cmp=com.abjjad.app/com.instabug.library.network.worker.uploader.InstabugSessionUploaderService } dcount=1}

### ISSUE THREAD

**Issue by mahmoudElfeel67** [Instabug/Instabug-Android#311]
### Steps to Reproduce the Problem
Cant reproduce
But the crash log is 
`
Caused by java.lang.IllegalArgumentException
Given work is not active: JobWorkItem{id=1 intent=Intent { cmp=com.abjjad.app/com.instabug.library.network.worker.uploader.InstabugSessionUploaderService } dcount=1}
android.app.job.JobParameters.completeWork (JobParameters.java:234)
androidx.core.app.JobIntentService$JobServiceEngineImpl$WrapperWorkItem.complete (JobIntentService.java:268)
java.lang.Thread.run (Thread.java:764)
`

### Instabug integration code
`new Instabug.Builder(this, getString(R.string.instabug_app_token))
                    .setInvocationEvents(InstabugInvocationEvent.SHAKE)
                    .setReproStepsState(State.ENABLED_WITH_NO_SCREENSHOTS)
                    .build();
            Instabug.setLocale(new Locale("ar"));
            BugReporting.setReportTypes(BugReporting.ReportType.BUG, BugReporting.ReportType.FEEDBACK);`

### SDK Version
    implementation 'com.instabug.library:instabug:9.0.5'
    implementation 'com.instabug.library:instabug-with-okhttp-interceptor:8.7.2.7-SNAPSHOT'
### Android Version
 Android 8.1.0 
### Device Model
 Griffe_T5

**Comment by mzelzoghbi** [comment]
Hello @mahmoudElfeel67 , Thanks for reporting this. This issue is related to androidX support libraries there are some open tickets on google issue tracker. However we did a workaround in further SDK Versions to fix that. So, Updating Instabug SDK Version to `9.1.5` should solve the issue.

We also noticed that you are using an interceptor version different from Instabug core SDK version. Please make sure you keep both versions the same to avoid any unexpected behavior.

And feel free to re-open the issue again if you encountered the same issue again.
Thank You 😊
