### ISSUE TITLE
NullPointerException at thread "Sdk start thread" when running tests

### ISSUE THREAD

**Issue by carstenhag** [Instabug/Instabug-Android#346]
### Steps to Reproduce the Problem
1. Update from Instabug 9.1.8 to 10.0.1 as dependency
2. Run unit tests (some with robolectric)

### Expected Behavior
Instabug should not cause exceptions etc. While it does not "break" the tests, it's still annoying to have, as I think the tests take longer to run now.

### Actual Behavior
`Exception: java.lang.NullPointerException thrown from the UncaughtExceptionHandler in thread "Sdk start thread"
` gets thrown about 100 times.

We have multiple brands, but only one brand has the Instabug 10.0.1 dependency in usage. The others user a custom no-op dependency in place of Instabug. This way I know for sure that the exceptions are caused by Instabug :).

### Instabug integration code
*Make sure to remove your app token.*

### SDK Version
target & compile sdk: 29

Similar to #340.

**Comment by carstenhag** [comment]
@Muhammadyoussef Hello there, can you please look at this? Our pipeline is having lots of OutOfMemory exceptions (only on the tests at the brand that uses instabug). While it may be unrelated, I think it is caused by Instabug.

**Comment by Muhammadyoussef** [comment]
Hi @carstenhag,

I apologize for any sort of inconvenience we are causing you so far 🙏 I created a snapshot for you that has a fix and also contains this [fix](https://github.com/Instabug/Instabug-Android/issues/347#issuecomment-719731428).

```
implementation 'com.instabug.library:instabug:10.0.1.6487-SNAPSHOT'
```

To consume the snapshot you will need to add the following to your app `build.gradle` as well
```
repositories {
    ....
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```
This snapshot is completely safe to use and has no debug code at all.

As for the OOM errors, we do not believe that it's caused by Instabug. I do recommend using [android test orchestrator](https://developer.android.com/training/testing/junit-runner#using-android-test-orchestrator) as it helps reducing shared states between the different test runs.

**Comment by carstenhag** [comment]
Hello there, with that snapshot version the errors are fixed, thanks 👍 .
