### ISSUE TITLE
UI problem with the in-app notification in dark mode

### ISSUE THREAD

**Issue by trongnkss** [Instabug/Instabug-Android#438]
Hi,
I got a problem where the reply button gets a blank text (or text in white) in the in-app notification popup in dark mode.
<img width="399" alt="Screenshot 2022-11-15 at 23 18 06" src="https://user-images.githubusercontent.com/88127003/201971026-eaf30615-e635-41f0-b358-8f78949a41c8.png">
Is there any way to fix the problem or custom this popup?

Thanks in advance

### Instabug integration code
*Instabug.Builder(this, BuildConfig.INSTABUG_KEY)
            .setInvocationEvents(InstabugInvocationEvent.SCREENSHOT, InstabugInvocationEvent.NONE)
            .build()
        Instabug.addTags(BuildConfig.BUILD_TYPE)*

### SDK Version
11.5.4 (also 10.13.0)

### Device Model
All models

### Android Version
API 29, 33

**Comment by mhashim6** [comment]
Hi @trongnkss, thanks for reporting this!

We’re currently looking into it and we’ll keep you updated.

**Comment by mhashim6** [comment]
Hi @trongnkss, Are you [customising](https://docs.instabug.com/docs/android-design) the theme or the color of the SDK?

If not you can configure the SDK to [show with dark theme](https://docs.instabug.com/docs/android-design#sdk-themes)

Also, you can [change the primary color](https://docs.instabug.com/docs/android-design#setting-the-primary-color) of the SDK.

I've attached some screenshots in dark mode
![Screenshot 2022-11-21 at 12 02 47 PM](https://user-images.githubusercontent.com/4984041/203022407-9d5a657d-4ebb-4dcc-94eb-33747512593c.png)
![Screenshot 2022-11-21 at 12 02 43 PM](https://user-images.githubusercontent.com/4984041/203022425-c2ba009a-618c-4ab4-a7e1-211852485304.png)


I'll close the ticket for now. Don't hesitate to open it if the issue is not yet resolved.
