### ISSUE TITLE
addPrivateViews does not mask UI in screen recordings

### ISSUE THREAD

**Issue by patrickcapadmi** [Instabug/Instabug-Android#474]
### Steps to Reproduce the Problem
1. Set view(s) to mask using `Instabug.addPrivateViews(...)`
2. Create an issue and take a screen recording

### Expected Behavior
Views marked as private are not visible in screen recordings.

### Actual Behavior
Views marked as private are visible in screen recordings captured via the Instabug SDK. Views are correctly obscured in screenshots.

### Instabug integration code
```Instabug.addPrivateViews(view)```

### SDK Version
12.7.1

### Device Model
Samsung S20 / Android 10
Pixel 7 / Android 14

**Comment by MohamedHefny** [comment]
Hello @patrickcapadmi 👋🏻
Thanks for reaching out, the `Instabug.addPrivateViews` API is meant to work with screenshots it's not supporting video recordings due to the limitations in the Android's media projection.

Please check our [documentation for Android](https://docs.instabug.com/docs/android-repro-steps#section-private-views) to learn more.

I'll close this for now as it's not an issue, and please feel free to open it again if you still have any inquiries.
