### ISSUE TITLE
Decrease the SDK's methods counts

### ISSUE THREAD

**Issue by 2x2xplz** [Instabug/Instabug-Android#59]
Recent versions of Instabug have added larger dependencies and more of them. Upgrading to v.4 pushed my project's method count over the 65k DEX limit. Of course base Android and the support libraries share the blame but we can't do anything about those. However, if someone isn't using RXJava, Instabug v.4's dependencies add over 15,000 methods -- RXJava, JCodec, and over 5000 in instabug-core. V.2 only added about 7,000, between RX and Instabug's own (no JCodec).

http://www.methodscount.com/?lib=com.instabug.library%3Ainstabug%3A2.6.2

http://www.methodscount.com/?lib=com.instabug.library%3Ainstabug%3A4.0.10

http://www.methodscount.com/?lib=com.instabug.library%3Ainstabug%3A4.2.8

Repeating what I stated in the previous issue I submitted, you've created a good product but I think you are going overboard with added features that are often not needed or wanted. A (much) smaller, tighter, "basic" SDK would likely be quite popular, in my opinion.

**Comment by msoliman** [comment]
Thanks @2x2xplz for the suggestion. I agree that we've got a way to go in terms of minimizing the methods count. We've been working on have different parts of the SDK being pluggable instead of having the SDK as a whole, and we're releasing this soon. In the next few months, we'll be working on cutting down the number of dependencies that the SDK depends on; including RxJava and JCodec.

I'll leave this open to keep you posted on our progress with this.

**Comment by robholmes** [comment]
I simply cannot use Instabug because of this, I use Proguard (even in debug) to reduce everything to enable my app to stay under the 64k limit. With Android support libraries, RxJava 2, Play Services, Firebase, Dagger 2, Retrofit, etc. this currently stands at around 48k. Adding Instabug instantly drives my app over the limit.

I just can't warrant switching to using multidex just to include Instabug, so for now I'll have to go without or seek an alternative.

**Comment by Korazy** [comment]
Hey @robholmes 

We currently use rxjava 2. I hope that helps :)

**Comment by 2x2xplz** [comment]
Had high hopes that you were making progress on reducing the method count. I tried implementing v8.0.1 in my latest build, only to find it was responsible for 23,800 methods!!! Core Instabug was nearly 8000, ReactiveX was over 10,000 and JCodec was about 5,500. 

It's nice that you simplified the API by breaking out the features into different classes, but even if you excluded 3 of 4 classes, you'd only save 3,000 methods or so.

Yes, Google Play and the support libraries are huge. But they provide the whole platform. Other service providers -- other bug reporters, notification services, database API, HTTP libraries, etc -- none come anywhere close to the resources used by Instabug.

I don't anticipate that you'll refactor your entire library to eliminate JCodec or Rx, so I doubt you'll ever get under 20,000 methods. Your entire business relies on making things easier for developers, not harder -- please keep that in mind when you create your future roadmap.
